#!/bin/tcsh

mkdir -p www

\cp -rpf styles www/

\cp -rpf images www/

foreach i (template/*.template-html)
  echo creating: $i  to  www/$i:t:r.html
  perl template/insert-tags.pl $i > www/$i:t:r.html
end
