CARMEN_HOME = ../../../
include ../../Makefile.conf

MODULE_NAME = "FakeCam"
MODULE_COMMENT = "Publishes images from a file"

SOURCES = fakecam.c
TARGETS = libfakecam.a 

all: 

libfakecam.a: fakecam.o

# rules

include ../../Makefile.rules
